server:
  port: 18080

spring:
  application:
    name: homes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${SECRET_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

api:
  public:
    service-key: ${API_PUBLIC_SERVICE_KEY}
  applyhome:
    service-key: ${API_APPLYHOME_SERVICE_KEY}
  policy:
    youth:
        service-key: ${API_POLICY_YOUTH_SERVICE_KEY}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}