server:
  port: 18080

spring:
  application:
    name: homes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

api:
  public:
    service-key: ${API_PUBLIC_SERVICE_KEY}

external:
  lh:
    API_PUBLIC_SERVICE_KEY=b951bdde8630a80ec19994c36b3e9abe8aebcc482c55b810670ecc07180d3a81
